### ISSUE TITLE
Can we have the ability to adjust maxcll? I have a 650 nit OLED, not a 800 nits.

### ISSUE THREAD

**Issue by DitherMan420** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#10]
Just wondering how I can use this on my LG 27gr95qe-b. Peak brightness on this panel is only 650 nits, so your 800 nit ICC profile would cause clipping, right? Can we adjust peak brightness somehow?

**Comment by Speedtreee** [comment]
I'm interested as well. Want to test this with LG G3 1500nits. Which editor do I use to edit/convert the icc profile?

**Comment by ninlilizi** [comment]
Saaaame. My monitor does 1100nits. But I would be just as happy with a 1000nit profile.

**Comment by dylanraga** [comment]
For now, you could use [my tutorial](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646) to create a profile with your peak monitor luminance by inputting its value in the synthesized ICM creation. 

Alternatively, you could use one of these untagged profiles, and use CRU to modify your EDID MaxCLL readout.
[100 nits](https://drive.google.com/open?id=1pi1XGX7ms9805lUHBJZ9874klymOC5Sr&usp=drive_fs)
[200 nits](https://drive.google.com/open?id=1peFJ3A4esLrwY-MfueUEms5x51H0JRzG&usp=drive_fs)
[300 nits](https://drive.google.com/open?id=1peancBGZPAwkIIw33xZZuQHJHba1b0Id&usp=drive_fs)

**Comment by DitherMan420** [comment]
> For now, you could use [my tutorial](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646) to create a profile with your peak monitor luminance by inputting its value in the synthesized ICM creation.
> 
> Alternatively, you could use one of these untagged profiles, and use CRU to modify your EDID MaxCLL readout. [100 nits](https://drive.google.com/open?id=1pi1XGX7ms9805lUHBJZ9874klymOC5Sr&usp=drive_fs) [200 nits](https://drive.google.com/open?id=1peFJ3A4esLrwY-MfueUEms5x51H0JRzG&usp=drive_fs) [300 nits](https://drive.google.com/open?id=1peancBGZPAwkIIw33xZZuQHJHba1b0Id&usp=drive_fs)

Thank you sir. I'll look into this. Do you plan on adding the ability to set the peak brightness? If you can do that, then I think we are basically golden ;-).

**Comment by Jason-GitH** [comment]
> For now, you could use [my tutorial](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646) to create a profile with your peak monitor luminance by inputting its value in the synthesized ICM creation.
> 
> Alternatively, you could use one of these untagged profiles, and use CRU to modify your EDID MaxCLL readout. [100 nits](https://drive.google.com/open?id=1pi1XGX7ms9805lUHBJZ9874klymOC5Sr&usp=drive_fs) [200 nits](https://drive.google.com/open?id=1peFJ3A4esLrwY-MfueUEms5x51H0JRzG&usp=drive_fs) [300 nits](https://drive.google.com/open?id=1peancBGZPAwkIIw33xZZuQHJHba1b0Id&usp=drive_fs)

Hello again. I tried out these ICC Profiles and have set CRU to 800 nits for maxCLL and maxFALL. However, Windows is reporting the HDR peak brightness (maxTML) as 240 nits for all three profiles.

**Comment by DitherMan420** [comment]
> For now, you could use [my tutorial](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646) to create a profile with your peak monitor luminance by inputting its value in the synthesized ICM creation.
> 
> Alternatively, you could use one of these untagged profiles, and use CRU to modify your EDID MaxCLL readout. [100 nits](https://drive.google.com/open?id=1pi1XGX7ms9805lUHBJZ9874klymOC5Sr&usp=drive_fs) [200 nits](https://drive.google.com/open?id=1peFJ3A4esLrwY-MfueUEms5x51H0JRzG&usp=drive_fs) [300 nits](https://drive.google.com/open?id=1peancBGZPAwkIIw33xZZuQHJHba1b0Id&usp=drive_fs)

Hello, I am following up on behalf of Jason-GitH. The new insider version of win11 does not let you adjust peak brightness with CRU for the ICC profile.

Can you please post some sort of tool that lets you change this? Or can you please post additional versions at different nits? I need 650. Others need 1,000. Others need 1,500. Thank you!

**Comment by DitherMan420** [comment]
@dylanraga are you gonna add more profiles or add a tool to let us change peak nits? Or is this abandoned? No disrespect, but people have been asking for this since you originally released these profiles on Github. Just hoping you didn't abandon that promise :-)

**Comment by dylanraga** [comment]
I recently stumbled upon LittleCMS which should let me package the whole thing, but haven’t had time recently to mess with it due to work responsibilities and holidays.

**Comment by sergiogomez-91** [comment]
> > I have the exact same monitor and cannot change the nit with CRU since apparently a recent windows update is avoiding to change this... Did someone get the proper profile working for the LG 27gr95qe-b and is able to share it please? :)
> 
> did you manage to create/find profile for that monitor?

Nope.... And I was not able to make my profile following the tutorial either :(

**Comment by ABDX80** [comment]
> > > I have the exact same monitor and cannot change the nit with CRU since apparently a recent windows update is avoiding to change this... Did someone get the proper profile working for the LG 27gr95qe-b and is able to share it please? :)
> > 
> > 
> > did you manage to create/find profile for that monitor?
> 
> Nope.... And I was not able to create my custom profile following the tutorial either :(

Same here :((

**Comment by dylanraga** [comment]
Addressed with the new LUT tool
