### ISSUE TITLE
Do we need to enable "Use Windows display calibration" as described by PC Monitors?

### ISSUE THREAD

**Issue by Jason-GitH** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#12]
I am curious if we should be doing steps 6 and 7 described [here](https://pcmonitors.info/articles/using-icc-profiles-in-windows/)

![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/101422827/e6c1c7ed-7d9b-44eb-8041-36139cb183dd)

**Comment by dylanraga** [comment]
The calibration will apply either way, not sure it matters. I think it only matters for legacy VCGT application.
