### ISSUE TITLE
ICC isn't automatically applied on windows startup

### ISSUE THREAD

**Issue by WilliamLeGod** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#14]
I just notice this ICC isn't automatically applied on windows startup. Have to go in setting > system > display and then It will automatically apply (u can easily replicate this and notice the change in gamma)

Mneawhile, HDR icc profile from HDR calibration app always applied correctly on windows startup

Does any1 know a fix to this?

Thanks!

**Comment by Jason-GitH** [comment]
Yeah, this is really annoying. Wonder why it treats the Windows HDR Calibration app ICC profiles differently from these ICC profiles.

**Comment by dylanraga** [comment]
Interesting, they apply for me automatically on the latest Insider version. I can see the login page switch over to gamma 2.2. Unfortunately it’s hard to pinpoint since Windows A/B tests a bunch of things.
