### ISSUE TITLE
Why don't we have gamma issues in SDR mode? Doesn't Windows 11 use sRGB gamma for SDR mode as well?

### ISSUE THREAD

**Issue by DitherMan420** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#15]
What prevents black level raise in SDR mode if Win11 uses sRGB gamma always?

**Comment by dylanraga** [comment]
Windows only _assumes_ an sRGB transfer _encoding_ for SDR mode, but the monitor’s actual EOTF is almost always gamma 2.2. This mismatch is actually expected, and even macOS follows it.

HDR is different because there is no mismatch — the OS assumes and outputs the same ST2084 HDR transfer, and Windows emulates the sRGB transfer for non-HDR content.

**Comment by DitherMan420** [comment]
> Windows only _assumes_ an sRGB transfer _encoding_ for SDR mode, but the monitor’s actual EOTF is almost always gamma 2.2. This mismatch is actually expected, and even macOS follows it.
> 
> If you do end up calibrating your SDR mode and attach a characterized monitor ICC, then color managed profiles will transform the app content with a sRGB transfer.
> 
> HDR is different because there is no mismatch — the OS assumes and outputs the same ST2084 HDR transfer, and Windows emulates the sRGB transfer for non-HDR content. In a sense, Win11 HDR assumes the characterization of your display and always performs a transform for SDR.

Forgive my stupid questions, but if windows sends srgb gamm to your monitor, and monitors expect 2.2, is it the monitors that correctly do the transformation from srgb to 2.2?

**Comment by morphinapg** [comment]
> Forgive my stupid questions, but if windows sends srgb gamm to your monitor, and monitors expect 2.2, is it the monitors that correctly do the transformation from srgb to 2.2?

Monitor has no clue what gamma windows is sending

**Comment by dylanraga** [comment]
Windows doesn’t “send” the sRGB gamma to your monitor, it sends RGB pixel values. These values are encoded with the sRGB inverse transfer, initially meant to be displayed on a monitor that decodes them with the sRGB EOTF. But most monitors have a gamma 2.2 EOTF, and instead decodes content with that instead of sRGB because the OS isn’t aware what the monitor’s “gamma” actually is (unless you characterize it by applying a monitor color profile, in which the OS transforms color managed content from G2.2 into sRGB. But most people calibrate to G2.2 without applying a characterization ICC)

**Comment by DitherMan420** [comment]
> Windows doesn’t “send” the sRGB gamma to your monitor, it sends RGB pixel values, without knowing how the output monitor is going to decode them. These values are encoded with the sRGB inverse transfer, initially meant to be displayed on a monitor that decodes them with the sRGB EOTF. But most monitors have a gamma 2.2 EOTF, and instead decodes content with that instead of sRGB because the OS isn’t aware what the monitor’s “gamma” actually is (unless you characterize it by applying a monitor color profile, in which the OS transforms color managed content from G2.2 into sRGB. But most people calibrate to G2.2 without applying a characterization ICC)

So content/game creators anticipate this issue and create things with this conversion in mind? (for SDR)

**Comment by morphinapg** [comment]
> So content/game creators anticipate this issue and create things with this conversion in mind? (for SDR)

BT1886 is the standard to which most content is graded based on, although games typically have their own calibration tools, which are usually necessary as the default settings rarely look "correct".

On an OLED, BT1886 is 2.4 gamma. On an LCD, it tends to be closer to 2.2.

**Comment by DitherMan420** [comment]
> > So content/game creators anticipate this issue and create things with this conversion in mind? (for SDR)
> 
> BT1886 is the standard to which most content is graded based on, although games typically have their own calibration tools, which are usually necessary as the default settings rarely look "correct".
> 
> On an OLED, BT1886 is 2.4 gamma. On an LCD, it tends to be closer to 2.2.

Perhaps i just don't understand but we're saying that most web content and games are gamma 2.2, correct? But windows encodes with the conversion. So do contrnt creators anticipate this when they create stuff?

**Comment by morphinapg** [comment]
> Perhaps i just don't understand but we're saying that most web content and games are gamma 2.2, correct? But windows encodes with the conversion. So do contrnt creators anticipate this when they create stuff?

Content doesn't have gamma in it. BT1886 is a calibration standard that applies to different monitor types, and is usually the standard to which content creators calibrate their screens, so ideally, you'd want your screen to be calibrated to that standard to match what they saw.

However, as I said, for LCDs, 2.2 is a pretty close approximation, and is easier to calibrate for. Before BT1886 became a standard, 2.2 was a pretty common way to calibrate pc monitors, and sRGB is a slightly modified version of that. Because of tradition, and simplicity, many people still calibrate their screens to 2.2 today, and it's still a pretty close match to BT1886 if you have an LCD screen.

If you have an OLED (as I do) then 2.4 actually makes more sense, and matches the BT1886 standard exactly for displays with perfect black levels.

**Comment by DitherMan420** [comment]
> > Perhaps i just don't understand but we're saying that most web content and games are gamma 2.2, correct? But windows encodes with the conversion. So do contrnt creators anticipate this when they create stuff?
> 
> Content doesn't have gamma in it. BT1886 is a calibration standard that applies to different monitor types, and is usually the standard to which content creators calibrate their screens, so ideally, you'd want your screen to be calibrated to that standard to match what they saw.
> 
> However, as I said, for LCDs, 2.2 is a pretty close approximation, and is easier to calibrate for. Before BT1886 became a standard, 2.2 was a pretty common way to calibrate pc monitors, and sRGB is a slightly modified version of that. Because of tradition, and simplicity, many people still calibrate their screens to 2.2 today, and it's still a pretty close match to BT1886 if you have an LCD screen.
> 
> If you have an OLED (as I do) then 2.4 actually makes more sense, and matches the BT1886 standard exactly for displays with perfect black levels.

Thanks for the info. I do know that bt1886 is preferable for SDR content for movies/tv. I thought though that 2.2 is recommended for PC use?

**Comment by morphinapg** [comment]
>Thanks for the info. I do know that bt1886 is preferable for SDR content for movies/tv. I thought though that 2.2 is recommended for PC use?

Depends on how you use your pc. Is it mostly just web browsing? Maybe 2.2 would be better, but even then a lot of pictures and videos you'll see online are probably graded at BT1886 these days. If you watch a lot of videos and play games, BT1886 is probably better.

But if you have an LCD screen, it's not a big deal to keep using 2.2 as I said it's close enough and it's easier to do. Some people keep using 2.2 out of tradition too. Some people simply prefer it. Ultimately it's up to you.

**Comment by dylanraga** [comment]
> So do content creators anticipate this when they create stuff?

It’s actually a very perplexing but very real topic. If you want to go down that rabbit hole, read and follow this entire thread: (it’s still not resolved or straight-cut)

https://community.acescentral.com/t/srgb-piece-wise-eotf-vs-pure-gamma/4024/19

But in a nutshell, yes. Seasoned artists are aware of this mismatch, but rarely compensate for it. The norm is to simply color grade SDR in a dark room at 2.4 gamma (BT.1886), which should translate similarly when outputting gamma 2.2 in a brighter room.

**Comment by DitherMan420** [comment]
> > So do content creators anticipate this when they create stuff?
> 
> It’s actually a very perplexing but very real topic. If you want to go down that rabbit hole, read and follow this entire thread: (it’s still not resolved or straight-cut)
> 
> https://community.acescentral.com/t/srgb-piece-wise-eotf-vs-pure-gamma/4024/19
> 
> But in a nutshell, yes. Seasoned artists are aware of this mismatch, but rarely compensate for it. The norm is to simply color grade SDR in a dark room at 2.4 gamma (BT.1886), which should translate similarly when outputting gamma 2.2 in a brighter room.

Thanks. Just curious. Why do all calibration guides calibrate oled monitors to gamma 2.2, if bt.1886/2.4 is more accurate for OLED?

**Comment by morphinapg** [comment]
> Thanks. Just curious. Why do all calibration guides calibrate oled monitors to gamma 2.2, if bt.1886/2.4 is more accurate for OLED?

I don't think calibrating OLED to 2.2 is very common but yes if you do usually watch in a lit room it may be preferable for some although I would argue it's still better to calibrate to 2.4 and simply use a brighter peak white.

**Comment by DitherMan420** [comment]
> > Thanks. Just curious. Why do all calibration guides calibrate oled monitors to gamma 2.2, if bt.1886/2.4 is more accurate for OLED?
> 
> I don't think calibrating OLED to 2.2 is very common but yes if you do usually watch in a lit room it may be preferable for some although I would argue it's still better to calibrate to 2.4 and simply use a brighter peak white.

Example: tftcentral guide for my oled monitor. They calibrate to 2.2

https://tftcentral.co.uk/reviews/lg-27gr95qe-oled

**Comment by DitherMan420** [comment]
Like why are we taregting 2.2 with this ICC profile even, if 2.4 is better for OLED?

**Comment by DitherMan420** [comment]
> > Thanks. Just curious. Why do all calibration guides calibrate oled monitors to gamma 2.2, if bt.1886/2.4 is more accurate for OLED?
> 
> I don't think calibrating OLED to 2.2 is very common but yes if you do usually watch in a lit room it may be preferable for some although I would argue it's still better to calibrate to 2.4 and simply use a brighter peak white.

Even rtinga has the gamma at 2.2 for their calibration??

**Comment by dylanraga** [comment]
Because most people don’t view their monitors only on a dark room. In the daytime with windows open, using gamma 2.4 will output shadows that will be too dark to see. Hence gamma 2.2 is the pseudo-standard for casual viewing conditions.

**Comment by morphinapg** [comment]
> Because most people don’t view their monitors only on a dark room. In the daytime with windows open, using gamma 2.4 will output shadows that will be too dark to see. Hence gamma 2.2 is the pseudo-standard for casual viewing conditions.

If you use 100 nits for SDR. I calibrate SDR to 2.4 gamma at about 170 nits for lit room viewing.

**Comment by DitherMan420** [comment]
> Because most people don’t view their monitors only on a dark room. In the daytime with windows open, using gamma 2.4 will output shadows that will be too dark to see. Hence gamma 2.2 is the pseudo-standard for casual viewing conditions.

Oh ok. So 2.2 is the psudeo standard since people use their panels in a combination of dark and light settings?

So if I calibrated my SDR mode for my monitor to gamma 2.2, and adjusted the RGB to 6500k temp, could I simply change Gamma settings in the OSD to 2.4 instead? Or would that throw off the rgb settings? Or are they separate?  I use my panel in a dark room almost always.

**Comment by morphinapg** [comment]
If you wanted to use both, you would need two different calibrations

**Comment by DitherMan420** [comment]
> If you wanted to use both, you would need two different calibrations. If you just want 2.4, then just calibrate to that.

I'm new to calibrations so apologies. But if you change gamma, does that change the color temperature? So if i calibrate to gamma 2.2 6500k temp, and i change gamma to 2.4, does color temp change?

**Comment by morphinapg** [comment]
> > If you wanted to use both, you would need two different calibrations. If you just want 2.4, then just calibrate to that.
> 
> I'm new to calibrations so apologies. But if you change gamma, does that change the color temperature? So if i calibrate to gamma 2.2 6500k temp, and i change gamma to 2.4, does color temp change?

It would be close, but the greyscale calibration RGB adjustments would be based on the luminance levels of the 2.2 gamma, so the adjustments you made wouldn't be accurate for 2.4 gamma, as they would be affecting a different part of the panel than when you calibrated it.

**Comment by DitherMan420** [comment]
> > > If you wanted to use both, you would need two different calibrations. If you just want 2.4, then just calibrate to that.
> > 
> > 
> > I'm new to calibrations so apologies. But if you change gamma, does that change the color temperature? So if i calibrate to gamma 2.2 6500k temp, and i change gamma to 2.4, does color temp change?
> 
> It would be close, but the greyscale calibration RGB adjustments would be based on the luminance levels of the 2.2 gamma, so the adjustments you made wouldn't be accurate for 2.4 gamma, as they would be affecting a different part of the panel than when you calibrated it. Unless your panel is incredibly accurate, you'd be likely to see small shifts in the greyscale at different points if you look at a black to white gradient.

Just wanted to follow up on this, if you do not mind.

So I didn't professionally calibrate my OLED Ultragear 27gr95qe-b. All I did was set the RGB values to the values that rtings/tftcetnral recommends. I also set the panel gamma to 22. Then I clamped the color gamut with novideo_srgb.

My questions for you is whether changing the panel gamma to 2.4 would require me to re-do the RGB values? i didn't mess with greyscale or anything fancy like that. I literally just changed RGB values and Gamma on the panel. So would my RGB values still hold up if I changed gamma to 2.4? Or would they need adjusting.

Thank you!

**Comment by DitherMan420** [comment]
Also...I've read that most games are graded to gamma 2.2.....are you guys saying that's NOT the case, and games are graded to 2.4?

**Comment by dylanraga** [comment]
Changing your white balance RGB values should hold regardless if you picked gamma 2.2 or 2.4, unless the internal LUT of the monitor is finicky. This is because gamma should have no effect on the white point.

As for games being graded for gamma 2.2, continue to read the ACES discussion on the matter I linked above. It’s too complex to give a single answer, because studios and graders can be all over the place. The gist is, yes, SDR games are usually MEANT to be viewed on a monitor with 2.2 gamma, but that does not reflect its grading environment.

**Comment by DitherMan420** [comment]
> Changing your white balance RGB values should hold regardless if you picked gamma 2.2 or 2.4, unless the internal LUT of the monitor is finicky. This is because gamma should have no effect on the white point.
> 
> As for games being graded for gamma 2.2, continue to read the ACES discussion on the matter I linked above. It’s too complex to give a single answer, because studios and graders can be all over the place. The gist is, yes, SDR games are usually MEANT to be viewed on a monitor with 2.2 gamma, but that does not always reflect its grading environment.
> 
> YouTube deliveries are handles similarly. Most video views come from well-lit environments, on a phone or monitor that typically has a 2.2 gamma, NOT from a home theater with 2.4 gamma/dim lighting. But many professionals (not all) that grade for YouTube still color grade for gamma 2.4 in a dark room, because it will look similar to 2.2 once taken out into casual room lighting. People rarely (professionally) grade in gamma 2.2, because they can just apply a gamma 2.4 -> 2.2 preview during grading to see how it translates.

Thanks. This is all fantastic information. I really appreciate you taking the time to lay it all out.

So in a nutshell, 2.2 is the default gamma that monitor/TV calibrators use on their TVs for gaming. For home theater, bt.1886/2.4 gamma is preferable to use on your TV. This is from the TV viewing standpoint. Is this correct? So say I have a filmmaker mode and a game mode on my OLED. For filmmaker mode (home theater), I use bt.1886. For game mode (gaming), I use 2.2?

**Comment by dylanraga** [comment]
There are always exceptions, but that is mostly correct.

**Comment by morphinapg** [comment]
Changing gamma will affect RGB white balance values if they aren't just single RGB gain values, like if you use a 10pt or 20pt calibration. Although you should never copy someone else's calibration values for that, as every panel is different hence the need for calibration at all.

When it comes to games, it doesn't seem like there's any kind of standard for how the monitors are calibrated at game studios, but thankfully games almost always have their own calibration controls. ALWAYS USE THESE. First of all, it will make sure that no matter what your gamma is, the game will look right. Secondly, it will correct for any idiotic default settings so many games use. So many games look terrible at the default settings and absolutely need to have them modified to look right.

**Comment by Jason-GitH** [comment]
> Windows only _assumes_ an sRGB transfer _encoding_ for SDR mode, but the monitor’s actual EOTF is almost always gamma 2.2. This mismatch is actually expected, and even macOS follows it.
> 
> If you do end up calibrating your SDR mode and attach a characterized monitor ICC, then color managed profiles will transform the app content with a sRGB transfer.
> 
> HDR is different because there is no mismatch — the OS assumes and outputs the same ST2084 HDR transfer, and Windows emulates the sRGB transfer for non-HDR content. In a sense, Win11 HDR assumes the characterization of your display and always performs a transform for SDR.

Is the "washed out" look of SDR content in Windows HDR mode actually the correct look? Like, would SDR content in Windows SDR mode look like that if you had a monitor with sRGB gamma option?

**Comment by dylanraga** [comment]
Yes, if both your HDR and SDR calibration are decent, they should look identical.

**Comment by DitherMan420** [comment]
> Yes, if both your HDR and SDR calibration are decent, they should look identical.

Sorry to necro this thread, but just wanted to confirm something. In your Diablo 4 example, the "HDR" screenshot is from running the game in SDR with Windows HDR on, NOT diablo NATIVE hdr, correct?

**Comment by dylanraga** [comment]
That is correct.
