### ISSUE TITLE
Is it possible to change the ICC profiles to using the *.ICC extension instead of *.ICM? I wonder if this is causing inability of Windows to automatically your profiles after restart/WinAltB toggle.

### ISSUE THREAD

**Issue by Jason-GitH** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#16]
It has been reported that the ICC profiles provided here are not automatically reapplied after Windows restart or when toggling HDR mode with Win+Alt+B shortcut. You have to reapply the default ICC profile in Color Management or Windows Settings app each time, or toggle HDR within the Settings app. However, the ICC profiles generated by Windows HDR Calibration app are automatically reapplied.

I noticed the profiles provided here are in *.ICM format, while the Windows HDR Calibration app profiles are in *.ICC format. Do you think changing their format to *.ICC would resolve the above behavior?

**Comment by dylanraga** [comment]
You can rename between .icm and .icc, Windows should treat them the same.
