### ISSUE TITLE
Is there a point in using the 400 nits version if you have an OLED with ABL?

### ISSUE THREAD

**Issue by DitherMan420** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#17]
So most OLEDs only allow an average picture brightness of like 150-200 nits in SDR, meaning that if you were to use the 400 nits version with the content slider at 80%, you would get hit with ABL. Are the 300 and 400 nit versions meant for LCD screens? Am I missing something here? Is there any point to use the higher nit versons with an OLED?

Thanks!

**Comment by dylanraga** [comment]
> Am I missing something here? Is there any point to use the higher nit versons with an OLED?

Some people like to run their SDR content brightness at higher levels than their monitor can support stable. Those are for them, or yes, for mini-LEDs.
