### ISSUE TITLE
Are there plans to make more ICC profiles for gamma BT.1886/2.4 or with different maxTML/maxFFTML?

### ISSUE THREAD

**Issue by Jason-GitH** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#18]
Thanks so much for these awesome profiles and fixing our raised blacks in SDR. Just curious if there will be more profiles coming that correct for other gammas such as 2.4 or set maxTML and maxFFTML to other values (such as 1000 nits or 1500 nits).

**Comment by dylanraga** [comment]
You can try following along to [my tutorial](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646) to generate your own profiles with different target gammas and peak luminance. 

Or you can use [the script](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/7) by @mspeedo to apply different tone mapping parameters, while setting your color profile to one generated by the Windows HDR Calibration app.

If I can find a simple way to synthesize my own base ICMs and tags, then I could create an all-in-one utility to generate profiles from any input parameters.
