### ISSUE TITLE
Stuck on this mods settings

### ISSUE THREAD

**Issue by Tr0w87** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#20]
Since using this profile Windows won't detect my monitors nits above 400, even after wiping the profile from my PC.
Even removing my GPU drivers, reinstalling and using the HDR calibration tool it still says 400 in advanced display when I was getting 600 prior to trying out this icc profile.

**Comment by dylanraga** [comment]
Something in one of the recent Windows Insiders updates just kind of borked things.
