### ISSUE TITLE
Need help selecting the correct file and settings

### ISSUE THREAD

**Issue by yunuset** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#21]
THANKS A LOT. I have been trying hard to find the cause of the terrible blocky blacks on the auto-hdr content. Your profiles fixed that. However, I am not sure which of the profiles and brightness settings are best suited for my display. What would you recommend for a 500 nit display? Sorry to bother you, but you seem to be the only person who knows the issue at hand. Thank you again.

**Comment by dylanraga** [comment]
The profile you pick is unrelated to the peak brightness of your display. What matters is the SDR content brightness value you set in your HDR Display settings. The Instructions in the readme has a table for which profile you should select depending on your SDR content brightness value.

**Comment by yunuset** [comment]
The 4 profiles going from 100 to 400 nits result in exploding whites, regardless of the SDR brightness. Only the unspecified one seems to not have this problem. Also, the reported nits on DisplayHDR Test by VESA show 800 nits for the mentioned 4 profiles, and 240 nits for the unspecified one.

**Comment by dylanraga** [comment]
Apologies — the unspecified profiles are to be used with monitors with peak brightness values that are different from 800 nits. With it, it will use the peak brightness reported from your monitor/EDID. You can use CRU to change the peak brightness that is reported, but if it’s already reporting the correct value, then no need.

**Comment by yunuset** [comment]
Thanks, my display is 500 nits. I have tried changing the peak brightness with CRU and it changes the brightness of the desktop but the reported value does not change (240 nits). When HDR is disabled , thus also the selected color profile being disabled with it, DisplayHDR Test reports 500 nits as it should.
