### ISSUE TITLE
Black Crush

### ISSUE THREAD

**Issue by leeson865** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#22]
I've been trying the unspecified profiles as I have a Samsung S95c capable of 1400-1700nits depending on DTM. It's causing black crush in games like Cyberpunk 2077 so I went to check black levels on http://www.lagom.nl/lcd-test/black.php#blacktest.png

When I use the unspecified profiles here: https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/10 including matching the HDR content slider to the relevant nits value, my top row (1-5) of the Lagom LCD Black level test are all the same colour - pure black.

Is it intentional that the Lagom test would produce these results when using one of the profiles, or is this an indication of another issue?

**Comment by BreakPoints** [comment]
Samsung QD-OLED TVs have pretty bad black crush no matter what, my S95B is the same. Shadow Detail in the picture settings helps a small amount but also raises 0 out of being absolute black (pixels entirely off)

**Comment by leeson865** [comment]
Not to this extent, if I use the HDR calibration profile the squares look perfect so I don't think it's a tv issue.

**Comment by timothy003** [comment]
Lagom LCD tests were not designed for OLED displays with pure power transfer functions. The human eye can't see very dark objects next to very bright ones. To make the test work, zoom all the way into the first square at 500%, hide the scrollbars, and move the cursor away in addition to darkening the room and entering full screen. The eyes may take a few minutes to adjust to the darkness.

**Comment by dylanraga** [comment]
Like @timothy003 said, double check in a completely dark room to see if it’s truly crushed, or just so dark they’re not noticeable under some glare. That is actually the correct behavior — the first 2-4 boxes should _barely_ be visible, and imperceptible if you’re not in a dark environment. On my LG 42C2 with the profile, the first box appears, but requires me to be in the pitch black and zoomed into it to notice it.

**Comment by leeson865** [comment]
Thanks @timothy003 and @dylanraga - I tried as you advised and still cannot make out a difference between the squares in a dark room. I've attached an imgur link with both comparisons to HDR calibration profile and the SRGB-to-gamma2.2 profile:

https://imgur.com/a/35pMEPE

To my eye, the SRGB-to-gamma2.2 is crushed.

@dylanraga the behaviour you mentioned of just slightly being able to see the first square in a pitch-black room while zoomed in, that is what my HDR calibration profile is showing me.

What are your thoughts after seeing the photos above?

**Comment by dylanraga** [comment]
It looks like your display is rendering those first squares too dark, your ST2084 calibration is probably undertracking. The first step out of black with the piecewise sRGB EOTF should definitely be more noticebale, I can even distinguish it in normal room lighting. Here's pictures I took of mine

https://imgur.com/a/COqKhlV

_(EOS 70D / ISO 3200 / 0.5s / f3.5)_

**Comment by leeson865** [comment]
Thanks for the help @dylanraga - I dug into my TV settings to play with them and bingo - found the issue. For others using the Samsung 95C with these profiles, ensure that:

Contrast enhancer is set to "Off" (Mine defaulted to High which was the main issue)
You can also get slightly better results by setting shadow detail to -2 and ST.2084 to -1 - found a calibration video here: https://www.youtube.com/watch?v=GC2xfsBtLHA

It is now perfect, including no black crush in Cyberpunk 2077, and fixed black in Diablo 4.

Thank you for your help @dylanraga !

I only have one last question remaining: This profile can be enabled permanently and used in both Auto-HDR and HDR games on PC, unless it crushes blacks in a particular game in which case I switch back to my HDR Calibration Profile?

**Comment by Jason-GitH** [comment]
> It looks like your display is rendering those first squares too dark, your ST2084 calibration is probably undertracking. The first step out of black with the piecewise sRGB EOTF should definitely be more noticebale, I can even distinguish it in normal room lighting. Here's pictures I took of my LG 42C2:
> 
> https://imgur.com/a/fC7nYAt
> 
> _(EOS 70D / ISO 3200 / 0.5s / f3.5)_

I am also using an LG C2 42. Boxes 1-5 are crushed using these ICC profiles. All boxes are visible when using the HDR Calibration app ICC profile. For reference, I have the TV set to black level 50, Fine Tune Dark Areas 0, and Standard game mode.

**Comment by ensingerphilipp** [comment]
Something is going on here - once i switched from NVIDIA to AMD Gpu the same black crush issue now affects me with the profiles  - which did work perfectly when i still had the 3090 in my system.

**Comment by dylanraga** [comment]
Addressed with new LUT tool.
