### ISSUE TITLE
Question regarding white point

### ISSUE THREAD

**Issue by noniegamed** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#24]
Hi there
Please excuse the incoming noob question. It might not make any sense to you at all. Just bought an OLED, have 0 experience in displays and calibration.

I'm using a colour profile created with the windows calibration app in conjunction with mspeedo's autohotkey script to convert srgb to gamma 2.2.
Using this exclusively to fix win 11 auto HDR washed out colours, I don't really care about desktop or web SDR content within HDR mode. I use SDR mode for SDR content

Now concerning auto HDR... not sure how or why, but the SDR-HDR brightness slider actually impacts midtones in auto HDR. For this reason I always leave the slider at 0, since this seems more accurate when comparing auto HDR to a games native HDR. Leaving it at 0 also makes highlights pop more, since the disparity between dark and bright parts of the image is greater.

Is the white point the same thing as "SDR white screen luminance" in your Windows SDR content brightness table? If so, should I set the white point to 80 (corresponding with the slider at 0) in order to keep the auto HDR image more "accurate"?
Or am I just talking complete nonsense here and should leave it at the default of 200?

**Comment by dylanraga** [comment]
If you keep your SDR content brightness slider at zero, you can use the 100-nit profile, it’s close enough. Or just place your SDR content brightness value to 5 to have it match up with the usual SDR white point of 100 nits.

The content brightness slider acts as the reference SDR white point level for Auto HDR content, in the same way that adjusting your monitor brightness affects the midtones and highlights of SDR games in SDR mode. Ideally you should match this value to whatever white level you use for your SDR mode.
