### ISSUE TITLE
Unspecified profile

### ISSUE THREAD

**Issue by JoaoMXN** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#26]
Is it possible to make it available an unspecified profile with 2000 nits peak brightness (for use with SDR brighness of 30 in Windows)? I ask because CRU is currently bugged with Samsung TVs, I can't change the max luminance there and with the unspecified profile it shows 240 nits in the Windows settings page.

**Comment by dylanraga** [comment]
https://drive.google.com/file/d/1z_ulnF2iqgFs-WhPMibst7QOYnZnxWLn/view?usp=sharing
