### ISSUE TITLE
Activating ICC profile changes the minTML to 0.0100 and sRGB coverage reduced to 94%

### ISSUE THREAD

**Issue by Jason-GitH** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#27]
If I use these profiles, the Min Luminance is changed to 0.0100 and sRGB coverage is reduced to 94%. If I use the HDR Calibration app, the Min Luminance is 0 and sRGB coverage is 100%.

Edit: These changes can be reverted by using CRU and running restart64.exe AFTER applying ICC profile.

![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/101422827/acdea61f-4c4c-4f14-9e2f-2da128605c6e)

**Comment by DitherMan420** [comment]
I would also like to know the answer to this. Does it matter what the EDID/DXDIAG reports for the primaries? Does anything use these for HDR profiles? Or does it only use the luminance values?

**Comment by dylanraga** [comment]
I wouldn’t worry about what these values for HDR. The only one that really matters is max peak luminance. I’ve previously tested the min luminance value to make no difference in the content I tested it in, but I’m going to try another test later.

**Comment by dylanraga** [comment]
Took a picture of the Windows HDR Calibration final comparison to see if changing the min. luminance has any effect. It does not, confirming my past tesing that it currently does not seem to modify the tone mapping of any existing content that I know of.

https://imgur.com/a/jj0wgcu

**Comment by Jason-GitH** [comment]
> Took a picture of the Windows HDR Calibration final comparison to see if changing the min. luminance has any effect. It does not, confirming my past tesing that it currently does not seem to modify the tone mapping of any existing content that I know of.
> 
> https://imgur.com/a/jj0wgcu

Thanks! I don't think this issue is unique to your ICC profiles. A lot of people are having issues with recent Windows builds where applying ICC profiles or changing from SDR to HDR is causing EDID values to be changed/ignored resulting in altered sRGB primaries, minTML being changed to various values around 0.0100 nits, maxTML being locked to 240 nits, or Windows ignoring CRU changes to HDR static metadata.
