### ISSUE TITLE
Question regarding Black Crush in native HDR Content

### ISSUE THREAD

**Issue by ensingerphilipp** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#28]
Trying to understand this a bit better:

From what ive read here so far, using the Profiles crushes blacks for native HDR Content, right?
So when i use 2.4 Gamma instead of 2.2 blacks are crushed more for native HDR?

I ask because i would like to use 2.4 with my QD-OLED Monitor in dark room conditions, but im not sure if its worth if the trade off is that native HDR blacks are crushed hard 😔

Additional Question: Regarding the SDR Content Brightness Slider -> is this monitor independent and 30 always means 200 nits?. Because as far as i know my monitor can only do ~240 nits fullframe but using ~35 SDR brightness slider with in HDR on mode is a lot lower brightness on fullwhite screen than using 100% brightness in the Monitor OSD in SDR only mode.

**Comment by Jason-GitH** [comment]
These ICC profiles are only intended to be used when viewing Virtual SDR and Auto HDR content, not native HDR. If you use gamma 2.2 or 2.4 correction, you will black crush native HDR content. You should switch back to your default Advanced Color profile when viewing native HDR content.

The SDR Content Brightness is independent of the display. It sets the luminance value for SDR white. I'm not sure why you are seeing that discrepancy. It may have to due with ABL behavior of monitor.
