### ISSUE TITLE
Clarification "Enable the "Add as HDR Profile" Checkbox

### ISSUE THREAD

**Issue by jdkang** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#3]
**Windows Version:** 10.0.22621 Build 22621`

The instructions in the README state:

> Enable the "Add as HDR Profile" checkbox

Is this the same as adding as an "advanced" profile? (See below picture)

![2023-06-18 09_14_41-Associate Color Profile](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/1807929/38a62caa-61b2-4da7-b295-9c6b04ba8e3c)

**Comment by dylanraga** [comment]
An HDR color profile is technically an Advanced Color profile, so it may still apply the gamma table but I haven’t tested on Windows 10.

**Comment by ylor** [comment]
The verbiage discrepancy also appears to exist in Windows 11 22H2
![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/2200609/610b62b6-db44-4bef-857d-fd3d739eb91b)

**Comment by jdkang** [comment]
Yeah I'm also on 22H2. I guess it's just cosmetic?

![2023-06-18 22_48_21-Settings](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/1807929/ba361531-4787-4c19-8253-fd2034cbf6db)
