### ISSUE TITLE
LG 27GR95QE-B Monitor 580 nit correction (Gamer 1 profile)

### ISSUE THREAD

**Issue by Kotomoto007** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#30]
Hello. 

Can you please make a correction profile file which peaks at 580 nits (SDR 480 nits).
Its for lg 27GR95QE-B 240hz oled monitor.

Will really appreciate! Thanks.

**Comment by DitherMan420** [comment]
More like 600 (SDR 100 nits), thanks. No idea what is with you crazy people trying to run SDR at 480 nits. Also the internal clipping point on this monitor is 600, specifically 603 or 604 as per EDID.
