### ISSUE TITLE
Are you planning to finally release a tool that lets us make our own? Or is this abandoned?

### ISSUE THREAD

**Issue by DitherMan420** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#31]
Just wondering if you still plan on making a tool that lets use change the peak nits? Otherwise, can you please just simply upload a bunch of versions, ranging from like 400 to 1500? Please?

**Comment by ABDX80** [comment]
@dylanraga Any updates bro?
Using the tutorial post is just too complicated for noob users. Or maybe make a YT video on it?!

**Comment by Animesh-Does-Code** [comment]
Personally I use [this](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/7) autohotkey script by mspeedo, which does not change the peak nits reported to Windows and uses the value from your monitor. You can disable it on the fly for real HDR content, which should have this tonemapping fix disabled anyway as it can cause crushed blacks. After you've installed and configured the prerequisites, download the pastebin text file and change its extension to ".ahk" instead of ".txt" to be able to run it.

You just need to edit the script file and change "whiteLuminance" to the equivalent nits value as your preferred Windows "SDR content brightness" value, like shown here:

<img width="680" alt="Windows SDR content brightness at 100 (480 nits)" src="https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/143435411/6cecf2dd-b4cd-4602-ac00-e81824ff9f05">

I've set whiteLuminance to 480 in that image because my SDR content brightness was set to 100, which is equivalent to 480 nits SDR brightness. (Refer to [this](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm#windows-sdr-content-brightness-table) handy table to find out what nit value you should use for whiteLuminance)

<img width="521" alt="SDR content brightness value" src="https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/143435411/2178c6c4-7dcd-4752-86dc-25ac1bc096b3">

I also highlighted the "gamma" setting too since you might want to change that to something else depending on your display. For my Odyssey neo G7, 2.4 looked closest to how SDR mode displayed black levels, 2.2 was still a little too washed out. Your display might be fine with gamma 2.2 however.

As mentioned in the issues page I linked, use WIN+F2 to apply the tonemapping and WIN+F1 to reset all changes.

If you still want to change your peak nits for whatever reason, the Windows HDR calibration app can be used to do that and works fine alongside this script.

**Comment by Jason-GitH** [comment]
> If you still want to change your peak nits for whatever reason, the Windows HDR calibration app can be used to do that and works fine alongside this script.

Is there any way to create a single script file that could have separate keyboard shortcuts for gamma 2.2 and gamma 2.4?

**Comment by Animesh-Does-Code** [comment]
> Is there any way to create a single script file that could have separate keyboard shortcuts for gamma 2.2 and gamma 2.4?

Yes, if you know your way around creating autohotkey scripts, you definitely can. I'm no expert at that but I just edited the code that applied tonemapping and added two shortcuts just for gamma 2.2 and 2.4:

```
#F3::    ;Win
^+F3::   ;Ctrl Shift
  gamma := 2.2
  CREATE_LUT_FILE(whiteLuminance,blackLuminance,gamma)
  LoadCalibrationCurve("templut")
Return

#F4::    ;Win 
^+F4::   ;Ctrl Shift 
  gamma := 2.4
  CREATE_LUT_FILE(whiteLuminance,blackLuminance,gamma)
  LoadCalibrationCurve("templut")
Return
```

Add these lines under the F2 shortcut code: 
<img width="380" alt="sublime_text_2023-12-04_22-25-03" src="https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/143435411/79fa61c2-180b-408c-bf39-dc68dbdf0901">


Use WIN+F3 for gamma 2.2 and WIN+F4 for gamma 2.4

**Comment by Animesh-Does-Code** [comment]
> How would the Global Gamma being left at 2.2 affect the gamma being set to 2.4 in calibration curve section?

I don't think the "global" settings are being read at all in the script when you apply a new curve, it might just be to initialize the variable. I set the global luminance and gamma values to crazy numbers but they didn't affect the end result when using the shortcuts at all. Even deleting them didn't change anything, though I'd leave them as they are.

**Comment by ABDX80** [comment]
> Personally I use [this](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/7) autohotkey script by mspeedo, which does not change the peak nits reported to Windows and uses the value from your monitor. You can disable it on the fly for real HDR content, which should have this tonemapping fix disabled anyway as it can cause crushed blacks. After you've installed and configured the prerequisites, download the pastebin text file and change its extension to ".ahk" instead of ".txt" to be able to run it.
> 
> You just need to edit the script file and change "whiteLuminance" to the equivalent nits value as your preferred Windows "SDR content brightness" value, like shown here:
> 
> <img alt="Windows SDR content brightness at 100 (480 nits)" width="680" src="https://private-user-images.githubusercontent.com/143435411/287553477-6cecf2dd-b4cd-4602-ac00-e81824ff9f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjQzODYsIm5iZiI6MTcwMjcyNDA4NiwicGF0aCI6Ii8xNDM0MzU0MTEvMjg3NTUzNDc3LTZjZWNmMmRkLWI0Y2QtNDYwMi1hYzAwLWU4MTgyNGZmOWYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMDU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWZhMmFhNWE5NTg3YjBjMmI1YmY5M2Q4NjAwNDk1NTE5YzY4ODIyZGZiYjJiNzI0NTFlYzU4NGQ0N2EwMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHX0Fa1HqD7XWTKPTKKJOCYap5cH_WHYQVU-NQiBu38">
> I've set whiteLuminance to 480 in that image because my SDR content brightness was set to 100, which is equivalent to 480 nits SDR brightness. (Refer to [this](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm#windows-sdr-content-brightness-table) handy table to find out what nit value you should use for whiteLuminance)
> 
> <img alt="SDR content brightness value" width="521" src="https://private-user-images.githubusercontent.com/143435411/287554663-2178c6c4-7dcd-4752-86dc-25ac1bc096b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjQzODYsIm5iZiI6MTcwMjcyNDA4NiwicGF0aCI6Ii8xNDM0MzU0MTEvMjg3NTU0NjYzLTIxNzhjNmM0LTdkY2QtNDc1Mi04NmRjLTI1YWMxYmMwOTZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMDU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTViNzU3YTAxNmRjYWVmNmUxMGJiNWVlNTA0NTc4MWU0ODQwMDE4YjgyNmQxZTA1ZDI1MDEyYzFhNDc3N2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bvu9IYydh2sdPSPK_VOES-U5F629DKkWte7EBbQCgbw">
> I also highlighted the "gamma" setting too since you might want to change that to something else depending on your display. For my Odyssey neo G7, 2.4 looked closest to how SDR mode displayed black levels, 2.2 was still a little too washed out. Your display might be fine with gamma 2.2 however.
> 
> As mentioned in the issues page I linked, use WIN+F2 to apply the tonemapping and WIN+F1 to reset all changes.
> 
> If you still want to change your peak nits for whatever reason, the Windows HDR calibration app can be used to do that and works fine alongside this script.

Is Gamma 2.4 better for Neo G9 too?

**Comment by ABDX80** [comment]
> > Hey, this works amazingly well. I noticed that the minTML gets changed to 0.0100 nits when using the Windows HDR Calibration app in conjunction with this script but it will stay at 0 nits if HDR static metadata values are modified in CRU.
> 
> I just checked and yeah minTML does get set to 0.0100 nits with any HDR calibration app profile enabled, but it doesn't seem to be related to the script from what I can tell, as closing the script and even restarting my PC didn't make the calibration profile use exactly 0 nits like it should, even with a newly created calibration profile. Maybe it's a bug with the calibration app itself. Setting peak nits using CRU is definitely preferable if you can do it.
> 
> Alternatively, you can set peak nits with [set_maxtml](https://github.com/ledoge/set_maxtml) by ledoge if for some reason CRU doesn't work for you or you can't access the static metadata menu. This is the case for my monitor when using DSC, which is needed for 4K 165Hz on DisplayPort 1.4.

How do you use the Set_MaxTML? I don't see any .exe file. Could you please guide me?! @Animesh-Does-Code

**Comment by Animesh-Does-Code** [comment]
> Is Gamma 2.4 better for Neo G9 too? @Animesh-Does-Code

It most probably is, assuming you are using your monitor's default settings for gamma and contrast, and also have contrast enhancer set to "off" if you have that setting in your monitor. 

You could still visually verify if 2.4 is indeed the best setting by using [this](http://www.lagom.nl/lcd-test/black.php) black level test and switching between SDR and HDR modes in Windows. Turn local dimming off in your monitor completely for both SDR and HDR mode when you do this to get the most consistent view of what gamma setting is closest to your monitor in SDR mode.

> How do you use the Set_MaxTML? I don't see any .exe file. Could you please guide me?! @Animesh-Does-Code

You need to download the release.zip file which contains the .exe from the releases page and extract it into any folder. Then open terminal/cmd in that folder with the .exe and then type (for example) `set_maxtml 1 1000` and press enter, which sets your main monitor's peak nits to 1000. Change '1000' in that command to your preferred nit value.

**Comment by ABDX80** [comment]
> > Is Gamma 2.4 better for Neo G9 too? @Animesh-Does-Code
> 
> It most probably is, assuming you are using your monitor's default settings for gamma and contrast, and also have contrast enhancer set to "off" if you have that setting in your monitor.
> 
> You could still visually verify if 2.4 is indeed the best setting by using [this](http://www.lagom.nl/lcd-test/black.php) black level test and switching between SDR and HDR modes in Windows. Turn local dimming off in your monitor completely for both SDR and HDR mode when you do this to get the most consistent view of what gamma setting is closest to your monitor in SDR mode.
> 
> > How do you use the Set_MaxTML? I don't see any .exe file. Could you please guide me?! @Animesh-Does-Code
> 
> You need to download the release.zip file which contains the .exe from the [releases page](https://github.com/ledoge/set_maxtml/releases) and extract it into any folder. Then open terminal/cmd in that folder with the .exe and then type (for example) `set_maxtml 1 1000` and press enter, which sets your main monitor's peak nits to 1000. Change '1000' in that command to your preferred nit value.

Thanks for getting back!
Aha I see, I downloaded the wrong files. After downloading and extracting the "release.zip", running "set_maxtml.exe" opens CMD terminal but it closes itself immediately, same is the case even if I run it as Administrator.
I'm using the 'Unspecified Profile' OP provided.
Any remedies?
Thanks again!
@Animesh-Does-Code

**Comment by Animesh-Does-Code** [comment]
> Thanks for getting back! Aha I see, I downloaded the wrong files. After downloading and extracting the "release.zip", running "set_maxtml.exe" opens CMD terminal but it closes itself immediately, same is the case even if I run it as Administrator. I'm using the 'Unspecified Profile' OP provided. Any remedies? Thanks again! @Animesh-Does-Code

You need to run terminal in the folder that contains set_maxtml.exe, not the .exe itself. In Windows 11 you can right click in an empty space in that folder and you'll get an option to "Open in Terminal." Type that command from before in that new terminal window.

**Comment by ABDX80** [comment]
> > Thanks for getting back! Aha I see, I downloaded the wrong files. After downloading and extracting the "release.zip", running "set_maxtml.exe" opens CMD terminal but it closes itself immediately, same is the case even if I run it as Administrator. I'm using the 'Unspecified Profile' OP provided. Any remedies? Thanks again! @Animesh-Does-Code
> 
> You need to run terminal in the folder that contains set_maxtml.exe, not the .exe itself. In Windows 11 you can right click in an empty space in that folder and you'll get an option to "Open in Terminal." Type that command from before in that new terminal window.

Aha okay.
Dang it, no luck :(

This is what the error msg I get:

PS C:\Users\black\Downloads\Set_MaxTML> set_maxtml 1 1040
set_maxtml : The term 'set_maxtml' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ set_maxtml 1 1040
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (set_maxtml:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
Anything still wrong??
    
I tried 'set_maxtml' command beforehand "to get a list of the currently active monitors and their current maxTML values" but same error on this command too.
    @Animesh-Does-Code

**Comment by Animesh-Does-Code** [comment]
> Anything still wrong??
> 
> I tried 'set_maxtml' command beforehand "to get a list of the currently active monitors and their current maxTML values" but same error on this command too. @Animesh-Does-Code

I think Windows Terminal is running PowerShell instead of Command Prompt for you by default. In that case first type `cmd` to switch to command prompt and then run that command again. PowerShell doesn't run commands from your current folder location by default, but cmd does.

**Comment by ABDX80** [comment]
> > Anything still wrong??
> > I tried 'set_maxtml' command beforehand "to get a list of the currently active monitors and their current maxTML values" but same error on this command too. @Animesh-Does-Code
> 
> I think Windows Terminal is running PowerShell instead of Command Prompt for you by default. In that case first type `cmd` to switch to command prompt and then run that command again. PowerShell doesn't run commands from your current folder location by default, but cmd does.

Worked like a charm!
But there's an issue -- as soon I open display settings it reverts back to default value; I assume it's the same if I reboot the PC.
Any fix for this?
@Animesh-Does-Code

**Comment by Animesh-Does-Code** [comment]
> Worked like a charm! But there's an issue -- as soon I open display settings it reverts back to default value; I assume it's the same if I reboot the PC. Any fix for this? @Animesh-Does-Code

The readme page for set_maxtml says the peak nits value should persist until a reboot as long as you don't have an advanced color profile assigned to your monitor, which is probably re-applying when you open display settings. You might have an HDR calibration profile assigned which is causing that. 

Go to "Color Management" from your start menu, then either untick "Use my settings for this device" or select the calibration profile you've made under "Advanced Color" ICC profiles and click remove to stop Windows from reverting the nits value.

Unfortunately it won't persist after a reboot, which is a limitation of this program and we can't do anything about it for now:

> As long as you don't reboot, the set value seems to persist between switching from HDR to SDR and back, as long as you don't have an "Advanced Color Profile" assigned in Windows.

I'm not sure if the developer can do anything about it either, as it might be a Windows limitation.

**Comment by dylanraga** [comment]
You can try following my new [alternative procedure](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm#alt-sln) to generate/apply your own LUT. Use the profile generated from Windows HDR Calibration.
