### ISSUE TITLE
1000 Nits, with HDR Slider 30 / 200 nits, ICC Profile please, i tip you 10$

### ISSUE THREAD

**Issue by yesyoyes** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#32]
Hello,

can u please make a ICC Profile with 1000 Nits Max Peak Brightness and Windows 11 HDR/SDR Slider 30 / 200 nits?

Please i cant figure out your Guide to create one manually, i will tip you 10$.

Thanks for your Time.

Greetings!

**Comment by dylanraga** [comment]
https://drive.google.com/file/d/1zkjgYYKJln0bogoGJ-875JPkTJjFV58h/view?usp=sharing

**Comment by yesyoyes** [comment]
@dylanraga thank you so much sir!

whats your Paypal for the tip?

**Comment by Kotomoto007** [comment]
> Hello,
> 
> can u please make a ICC Profile with 1000 Nits Max Peak Brightness and Windows 11 HDR/SDR Slider 30 / 200 nits?
> 
> Please i cant figure out your Guide to create one manually, i will tip you 10$.
> 
> Thanks for your Time.
> 
> Greetings!

Why do you need such small sdr brightness and not full 480?
