### ISSUE TITLE
D65 1000nit 2.4 gamma profile

### ISSUE THREAD

**Issue by ZhouRen777** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#33]
Is it possible for you generate one? i know used LG oleds but us on qd oleds D65 looks fine and 2.4 gamma is perfect for Dark room/night gaming

**Comment by dylanraga** [comment]
You can try following my new [alternative procedure](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm#alt-sln) to generate/apply your own LUT. Use the profile generated from Windows HDR Calibration.
