### ISSUE TITLE
Blacks crushing severely using AMD Radeon GPU

### ISSUE THREAD

**Issue by ensingerphilipp** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#36]
Switched from RTX 3090 to RX 7900 xtx and suddenly the profiles that always worked resulted in severe black crush and Color shift on my OLED. All adjustable filters on driver level are disabled.

To achieve the same Black Level Gamma 2.2 experience i had working perfectly with NVIDIA Gpu i now have to go to Gamma 1.55, which totally throws off something in the colors i can not specifically name or pinpoint. So this is not a working solution either. 

Gamma 2.2 = Severe Black Crush in SDR Content
Gamma 1.55 = Black crush fixed (Black Levels equal to 2.2 on rtx 3090), severe color shifting / saturation missing

Tried using ahk script as well as dispwin solution in releases
Any idea what might be the problem? 

Driver Version 23.30.01

**Comment by dylanraga** [comment]
I'm guessing that AMD might be ingesting the LUT in a different reference space than NVIDIA's. Could you run `dxdiag.exe`, hit the Display tab, press "Save All Information..." into a text file, and send me its contents?

**Comment by ensingerphilipp** [comment]
[DxDiag_RX7900XTX.txt](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/files/13833653/DxDiag_RX7900XTX.txt)

Output here :) - thx!

**Comment by dylanraga** [comment]
Nothing that stands out there. Could you try if this LUT cal looks correct?

https://pastebin.com/1pyVpL0r

(SDR 200nits, gamma 2.2)

**Comment by ensingerphilipp** [comment]
This one looks a lot better than when i generate a 200nit gamma 2.2 with your web tool or use the ahk script!!
It is not there 100% yet tho as some near black values are still crushing. In a test video where i can see most of the grey and blacks in a dark room in SDR some of them still go missing in HDR with your lut applied. 

But this is now 90% there . before i as only seeing black for all of they greys in the test video haha.

**Comment by ensingerphilipp** [comment]
Here is a very unscientific comparison ( i tried adjusting the pics so they look like they do in real):
HDR Off and NVIDIA HDR adjusted (lut applied) do in reality show exactly the same amount of blacks and greys.
The Green color shift you see in the pictures also is not real (smartphone camera)

**No HDR default:**

![noHDR_default](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/45814205/3cf0c6bb-1087-40ca-aa35-cea394e737d7)

**HDR Nvidia adjusted**

![HDR_Nvidia_adjusted](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/45814205/8c636ddd-ba76-40ea-9c44-94c2776aa2c4)


**HDR Amd adjusted**

![HDR_AMD_adjusted](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/45814205/60454171-b1d5-41b2-9ddf-589d388eb773)


**HDR AMD NEW Adjusted**

![HDR_AMD_NEWadjusted](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/45814205/3dfdda0b-552e-4d4e-9c45-d891df0a28e3)

**Comment by dylanraga** [comment]
I've updated the web LUT tool for AMD LUTs. I've also added another field for black floor, which you can raise if you're experiencing black crush. I recommend increasing this in intervals of 0.05 until you're happy with your image.

<img width="530" alt="image" src="https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/10266277/7faa8198-8071-478e-9300-a90f12a34954">

**Comment by ensingerphilipp** [comment]
Thansk a lot will test this tomorrow :)

**Comment by ensingerphilipp** [comment]
Actually tested right now - works perfectly thanks a lot :) 0.15 did it for me
