### ISSUE TITLE
How to determine a good SDR white point?

### ISSUE THREAD

**Issue by RitzyBusiness** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#37]
I don't really understand what a good value would be for my monitor or how to calculate it. Help on how to figure this out would be highly appreciated, otherwise I'm just shooting into the dark with values 🤣

**Comment by dylanraga** [comment]
If you're in a normal office setting, I would start with 200 nits, which corresponds with a Windows Content Brightness Value of 30 in Window's Display Settings.

If you're usually in a darker room with controlled lighting, I would recommend going lower to either 160 (CBV 20) or 120 (CBV 10) to maximize your HDR headroom. In this case, feel free to also try Gamma 2.4, which is what's used for professionally color grading in most SDR content. If you're experiencing black crush, raise the Black floor in intervals of 0.05 until you have a clean image.

**Comment by RitzyBusiness** [comment]
Thanks much, that is a good explanation.
