### ISSUE TITLE
does this work for Windows 10?

### ISSUE THREAD

**Issue by Kilrua** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#4]
Does Windows 10 need this fix? I use Special K for most my HDR Gaming so really not sure if there's a noticeable difference on Windows 10.

**Comment by dylanraga** [comment]
I haven’t tested if it works on win10, but some people mentioned it works by adding it is an Advanced Color profile (rather than HDR). I’m not sure if you can change your SDR brightness on Win10, though. It should improve on Special K.

**Comment by Kilrua** [comment]
![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/12567974/f64ddd3e-a600-4f21-a339-cd6a9cf24159)
Here is the SDR brightness slider in Windows 10, not sure if it's the exact same thing as 11.

**Comment by dylanraga** [comment]
Should be all good then, just follow the provided instructions.

**Comment by Kilrua** [comment]
Hmm, I tried the highest and lowest profile and there doesn't seem to be a noticeable difference in colors on desktop. Made sure NVCP has reference mode off. Assuming clicking close/OK after adding the advanced profile should bring immediate change I guess I'll have to poke around to see if anything with my system is preventing the change.

**Comment by dylanraga** [comment]
To see a change, you also need to set the profile as your default, and you need to be in HDR mode.

**Comment by Kilrua** [comment]
I set it as default and I'm always in HDR Mode. Still no difference. I've heard sometimes ICCM profiles just don't work so maybe that's it.

**Comment by Kilrua** [comment]
I set it as default and I'm always in HDR Mode. Still no difference. I've heard sometimes ICC profiles just don't work so maybe that's it.

**Comment by Kilrua** [comment]
/
