### ISSUE TITLE
When using autoHDR and using the 400 nits ICC profile, should my SDR brightness slider be set to 80?

### ISSUE THREAD

**Issue by abood101** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#45]
Sorry noob here!

Usually in autoHDR when the game is native sRGB, I use my windows calibrated icc profile and set SDR brightness slider to 0.

But when game is native gamma 2.2 and I use one of the ICC profiles provided by @dylanraga (i have qdoled aw3423dw so i just use the highest profile which in this case is 400 nits) should i set my SDR brightness slider to 80 in that case?

**Comment by dylanraga** [comment]
My two cents is that your SDR brightness should be the same in both scenarios, ie 0 if you prefer that for autoHDR. In that case, you would use the 100-nit ICC profile (peak brightness will still be the same).

Optimally, you would use the profile generated by the Windows HDR Calibration app and apply the curve transformation via the [alternative procedure](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm?tab=readme-ov-file#alternate-procedure--custom-profile).

**Comment by abood101** [comment]
Okay so I followed the alternative procedure.

For my aw3423dw qdoled I generated a LUT with SDR white at 1000 nits which becomes windows content brightness 230

I followed the rest of the steps and ran srgb-to-gamma.bat 

So now its safe to assume that the windows calibrated profile has the gamma 2.2 curve applied to it? Or should I create a new windows calibrated profile once more since when I was doing these steps I already had a windows calibrated profile?

**Comment by dylanraga** [comment]
You definitely don't want your SDR white to be at 1000 nits, your monitor does not even support that level of brightness past a 3% window. Your SDR brightness is the brightness of SDR content on your screen rendered in HDR mode, _not_ the peak brightness of your display. Rendering your entire desktop at 1000 nits would likely be blindingly bright, if your monitor supported it. Ideally then, this value should be below the fullfield brightness capabilities of your monitor, which is about 250 nits for the AW3423DW. Therefore your Windows Content Brightness Value should be below 40 -- I'd start at a value of 30, or 200 nits, which is usually the most common brightness for monitors in normal office lighting.

**Comment by abood101** [comment]
Yeah I think i will just use the 100 nits s/ brightness 5 profile and call it a day.

When using that profile, my sdr slider should be set to 5 right?

**Comment by dylanraga** [comment]
Correct
