### ISSUE TITLE
Potential black floor issue

### ISSUE THREAD

**Issue by mspeedo** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#5]
Hi @dylanraga , by checking your graph "srgb vs gamma 2.2 curve comparison" https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/blob/main/srgb_vs_g22.png  it seems gamma 2.2 curve should hit black floor before piecewise srgb.

But when I create graphs from your Excel document for 100 nit and 200 nits SDR brightness, black floor is always reached at PQ code 0 because there is smooth rolloff to 0. 
Shouldn't there be a hard cut off to reach 0 PQ luminance sooner, somewhere around 0.03 nits (PQ code 37) for example? What do you think, thank you.

**Comment by dylanraga** [comment]
The Y-axis in that chart is logarithmic -- it will never reach down to zero. Any transfer curve hit should hit black (0 nits) at exactly the same spot, at pixel value 0. Raising it to a higher value can introduce color banding.

[Here's a chart comparing gamma-2.2 and sRGB](https://i.imgur.com/M00kSQp.png) with the Y-axis scaled w.r.t. ST2084, reaching down to zero.

PQ luminance in the sheet refers to the ideal screen-referred luminance on a perfect ST2084 display. What my profile is doing is mapping this ideal response to one such that, when mapped onto sRGB, actually maps onto gamma 2.2. In the case of many consumer displays, their SDR is also mostly calibrated towards a pure 2.2 gamma power, with no early cut-off or offset.

Clipping all PQ signal values below 37/1023 would crush all SDR gamma-2.2 pixel values below 6/255 (ref 100nits), which would be terrible. You can view this image to test your black rendering:

http://www.lagom.nl/lcd-test/black.php#blacktest.png

Ideally, your display should be able to distinguish between the first box and true black when viewed in a dark room. If not, your display is crushing shadow details. Crushing the first six boxes would make shadows appear blotchy and would destroy image fidelity.

Now, if you wanted to artificially raise the black floor tone mapping in response to your display being non-OLED with a certain black luminance (e.g. 0.03 nits), or wanted to tone map for veiling screen glare, you could try raising Black luminance field the sheets, which adds a black offset. This will only look proper if your monitor itself doesn't add its own black-offset tone mapping for HDR10.

**Comment by mspeedo** [comment]
Thanks @dylanraga, my intention was to use your profiles as a fix for HDR games which have "raised blacks" issue. Nice example is Cyberpunk, this video explains the issue with visual reshade histogram https://youtu.be/jPmtvUCJORU
Basically, game will never output true black signal, if it outputs 0.2 nits or so, it was intended to be pure black. It can be fixed via reshade plugin by adjusting the black point as seen on that video, but the same could be actually done also with your profiles with custom/adjusted mapping curve, but we need to "cut" black floor the same as in that reshade plugin. 
But yes there is nothing wrong in your sheet calculations, this fix just needs different approach on how to create custom calibration curve.

**Comment by dylanraga** [comment]
On case-by-game basis, I would just recommend using ReShade to lower its black floor. Though if you really wanted to do it via a profile, then just zero out all the R/G/B values below your luminance point's pixel value.

**Comment by KoKlusz** [comment]
@mspeedo Using this fix with CP2077 will give the exact same black level as in SDR with default in game brightness / gamma setting. If that not enough I would then look into reshade, I would be careful with that, however. Because of modern games tone mapping / eye adaptation algorithms it's hard to say when a game is supposed to reach perfect black and when not. So if you tune one scene to look good, you might still get raised black in the second scene but then crushed shadows in the third.
