### ISSUE TITLE
srgb-to-gamma.bat not working with 2 monitors

### ISSUE THREAD

**Issue by AnouarSGS** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#55]
Hi,

I am not sure if this is a new issue. When I am using 2 monitors and run srgb-to-gamma.bat, the lut.cal change doesn't get applied.

When I disable 1 monitor and keep the other on, srgb-to-gamma.bat works again.

Note: I have 1 monitor that has HDR on and the other one does not.

**Comment by jellyatom** [comment]
I am having the same issue; the gamma is being changed on my second (non-HDR) monitor.

**Comment by NJinsei** [comment]
Found a fix, edit the "srgb-to-gamma" file and go through the displays(-d [n])  from 1 numerically, so for me ".\dispwin.exe" "-d 2" ".\lut.cal" worked.

**Comment by jellyatom** [comment]
> Found a fix, edit the "srgb-to-gamma" file and go through the displays(-d [n]) from 1 numerically, so for me ".\dispwin.exe" "-d 2" ".\lut.cal" worked.

Amazing, thank you!

**Comment by AnouarSGS** [comment]
> Found a fix, edit the "srgb-to-gamma" file and go through the displays(-d [n]) from 1 numerically, so for me ".\dispwin.exe" "-d 2" ".\lut.cal" worked.

Thanks a lot, you're a legend

**Comment by oxidodeazufre** [comment]
> Found a fix, edit the "srgb-to-gamma" file and go through the displays(-d [n]) from 1 numerically, so for me ".\dispwin.exe" "-d 2" ".\lut.cal" worked.

tysm
