### ISSUE TITLE
Can you create profiles for 2.4 gamma?

### ISSUE THREAD

**Issue by morphinapg** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#6]
This is a great start but I would love to be able to apply 2.4 gamma to my SDR content in HDR mode, since I'm using an OLED monitor and have my SDR modes calibrated to 2.4 gamma.

Or what might be even better is if there was a tool to select any gamma at any brightness level. For example, I have SDR brightness set to 14 in Windows based on how it looks in my environment.

**Comment by dylanraga** [comment]
I posted a coarse procedure on how to generate your own profile for any given gamma & reference white on another issue.

https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646

I plan to write an automated tool to create them after I figure some things out.

**Comment by morphinapg** [comment]
Excellent, thank you

**Comment by dylanraga** [comment]
Addressed with new LUT tool
